version: 0.2

env:
  variables:
     IMG_NAME: "grassbian"
     ENABLE_SSH: "1"
     FIRST_USER_PASS: "pi"
     WPA_ESSID: "ESSID_REPLACE"
     WPA_PASSWORD: "PASSWORD_REPLACE"
     WPA_COUNTRY: "COUNTRY_REPLACE"
  #parameter-store:
     # key: "value"
  #git-credential-helper: yes

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      #- yum check-update
      #- yum -y update
      - yum -y install coreutils quilt quilt.noarch parted debootstrap zerofree qemu-user-static pxz zip dosfstools bsdtar libcap2-bin grep rsync xz-utils file git curl make kmod vim-common xz 
  #pre_build:
    #commands:
      # - command
  build:
    commands:
      - sed -i 's/^dependencies_check/#dependencies_check/' ./build.sh
      - ./build.sh -c extliburls
  #post_build:
    #commands:
      # - command
artifacts:
  files:
    - './deploy/**/*'
    # - location
  name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
cache:
  paths:
    - ./work/**/*
